Bugfix for using shortcut in an ember.js context
When using shortcut in an ember.js context, you get this error messages
every time you execute a shortcut in your web application.

Uncaught TypeError: _shortcutFns[_i] is not a function

The reason is, that Ember extends (aka monkey patches) the object class
which results in keys (aka values for _i), that are not present in
_shortcutFns.